Show hide unknown
cds-snc/cppd-medical-report pull request #73
Opened 2019-11-23 04:26 UTC by dsamojlenko

# Description

Show/hide "Why is the prognosis unknown?" field based on radio selection 

Also includes a change to how Vue is loaded - this change will require changes in #72 

# Test Instructions

- Navigate to add_condition
- Under 'Is your patient's condition likely to', select Unknown

2019-11-23 20:09 UTC, jeffmaher submitted a review, later dismissed
Tested in Firefox. LGTM. 🍕

2019-11-24 17:29 UTC, jeffmaher submitted a review, later dismissed

2019-11-25 14:10 UTC, CalvinRodo requested changes
I'm not seeing anything but localization keys in the PR, is that expected?

2019-11-25 15:17 UTC, CalvinRodo requested changes
Need to add validation for the unknown field, it needs to be required when the item is selected in the radio box.

2019-11-25 15:17 UTC, CalvinRodo commented on routes/add_condition/add_condition.njk
> +        {{ textArea('condition_outlook_unknown', 'add_condition.prognosis_unknown') }}
This should have `{ required: true }` since it's required when it's displayed.

2019-11-25 15:50 UTC, dsamojlenko commented
Added validation for all fields

2019-11-25 15:54 UTC, CalvinRodo requested changes
When submitting a page with nothing entered it displays the unknown field even if nothing is selected. No errors are associated with the field: 

![Screen Shot 2019-11-25 at 10 53 11 AM](https://user-images.githubusercontent.com/87738/69555947-f5560d80-0f71-11ea-9b80-b1b8380cf356.png)

2019-11-25 16:20 UTC, dsamojlenko commented
> When submitting a page with nothing entered it displays the unknown field even if nothing is selected. No errors are associated with the field:
> 
> ![Screen Shot 2019-11-25 at 10 53 11 AM](https://user-images.githubusercontent.com/87738/69555947-f5560d80-0f71-11ea-9b80-b1b8380cf356.png)

This issue will be resolved with an upstream change coming later today: https://github.com/cds-snc/node-starter-app/pull/133

2019-11-25 16:23 UTC, jeffmaher approved these changes
Works! 🍕

2019-11-25 16:46 UTC, CalvinRodo approved these changes

2019-11-25 16:47 UTC, merged