File Uploader improvements
cds-snc/cppd-medical-report pull request #74
Opened 2019-11-23 05:19 UTC by dsamojlenko

# Description

File Uploader improvements:
- improved styling
- enable remove link

# Test Instructions

- Navigate to add_condition
- Click Upload button and select a file
- Notice the lovely styling
- Try out the remove link

2019-11-23 20:36 UTC, jeffmaher submitted a review, later dismissed
Works in Firefox! LGTM 🍕 . Left one non-blocking comment.

2019-11-23 20:36 UTC, jeffmaher commented on assets/js/components/FileUpload.vue
> +    console.log('Component ready.')
Stray `console.log`?

2019-11-23 23:55 UTC, dsamojlenko commented on assets/js/components/FileUpload.vue
> +    console.log('Component ready.')
yup, removed ... there was another one just above.

2019-11-24 17:29 UTC, jeffmaher submitted a review, later dismissed
🍕

2019-11-25 14:20 UTC, CalvinRodo requested changes
I'm not getting styling browser is chrome: 

![Screen Shot 2019-11-25 at 9 20 31 AM](https://user-images.githubusercontent.com/87738/69548171-d8670d80-0f64-11ea-8f6c-597acc63f7e6.png)

and also 

The contrast on the text: `These could include: clinical notes, specialist reports, or hospital discharge reports, etc` is not accessible. 

Error text from Axe-Chrome: 

>Element has insufficient color contrast of 1.48 (foreground color: #cbd5e0, background color: #ffffff, font size: 15.6pt (20.8px), font weight: normal). Expected contrast ratio of 4.5:1

Although i notice that text is not part of this PR, but it seems related in scope to this PR so flagging it here.

2019-11-25 14:23 UTC, CalvinRodo commented
The contrast on the text: `These could include: clinical notes, specialist reports, or hospital discharge reports, etc` is not accessible. 

Error text from Axe-Chrome: 

>Element has insufficient color contrast of 1.48 (foreground color: #cbd5e0, background color: #ffffff, font size: 15.6pt (20.8px), font weight: normal). Expected contrast ratio of 4.5:1

2019-11-25 15:26 UTC, dsamojlenko commented
Fixed the heroku Review App issue here - need to include .vue files when purging css

2019-11-25 15:30 UTC, jeffmaher approved these changes
🍕

2019-11-25 16:47 UTC, CalvinRodo approved these changes

2019-11-25 17:11 UTC, merged