Translate Section 6 to French
cds-snc/cppd-medical-report pull request #91
Opened 2019-11-27 13:57 UTC by jeffmaher

# Description

[Trello card:](https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr) Translates section 6 of the medical report into French

# Test Instructions

1. Go to the application (from the linked "View Deployment")
1. Change the URL to `.../fr/frsection6` from `.../en/section6`)
1. See French translation (original EN and FR forms are linked in the [Trello card](https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr))

# Help Requested

If there are any things you spot that are issues we should come back to, but are out of scope of just the direct translation, please add a new Trello card or [use this one to quickly add a note to the checklist](https://trello.com/c/WqJVeqsh/356-misc-content-tasks). I've already added a few from section 6 to that card, around the conditional questioning.

2019-11-27 13:58 UTC, jeffmaher commented
@keithiopia : Could you review? Ping back here if updates are needed. If things look OK, assign to Dave for code review.

2019-11-27 14:25 UTC, keithiopia commented
> @keithiopia : Could you review? Ping back here if updates are needed. If things look OK, assign to Dave for code review.

I might not have time today 😬 If it can wait till tomorrow, then I'm all over it.

2019-11-27 16:21 UTC, CalvinRodo requested changes

2019-11-27 16:21 UTC, CalvinRodo commented on locales/en.json
> +  "section6.stop_work_not_discussed": "section6.stop_work_not_discussed",
Missing english text

2019-11-27 17:20 UTC, jeffmaher commented on locales/en.json
> +  "section6.stop_work_not_discussed": "section6.stop_work_not_discussed",
Got it! Added in.

2019-11-27 17:21 UTC, jeffmaher commented
@keithiopia : No prob. @sidewalkballet : Do you have time to take over?

2019-11-27 19:46 UTC, courtneycl submitted a review, later dismissed
LGTM. I added a checklist entry in the misc tasks trello card about the validation needing to be translated.

2019-11-27 19:59 UTC, jeffmaher commented
Back over to you @CalvinRodo

2019-11-28 13:48 UTC, CalvinRodo submitted a review, later dismissed

2019-11-28 15:17 UTC, jeffmaher commented
I'm working on merge conflicts

2019-11-28 15:34 UTC, jeffmaher commented
All merged in

2019-11-28 15:36 UTC, CalvinRodo approved these changes
🉑

2019-11-28 15:37 UTC, merged